### ISSUE TITLE
netcdf4 is pinned to an old version 1.4.1

### ISSUE THREAD

**Issue by ocefpaf** [cormorack/yodapy#111]
Based on the comment in the requirement.txt file looks like the problem is not really netcdf4 for a newer netCDF-C.

See https://github.com/Unidata/netcdf-c/issues/1299

A workaround is to add `#fillmismatch` at the end of the URL or to fix the metadata.

**Comment by lsetiawan** [comment]
This is the solution that I need! Thanks! Will make a PR soon.

**Comment by ocefpaf** [comment]
I would recommend merging #114 before any code change to avoid conflicts.

PS: how are you planning on fixing this issue? adding a `f"'"{url}#fillmismatch"`  workaround or fixing the offending metadata? The former is quick and easy to do here but the latter is, in theory, the "right way."

**Comment by lsetiawan** [comment]
I can't change the offending metadata since that's an OOI CI issue, so I'm adding the `#fillmismatch` in the mean time.
