### ISSUE TITLE
Windows problems

### ISSUE THREAD

**Issue by s-kganz** [cormorack/yodapy#32]
$Home not set on Windows, small workaround found by modifying netrc library to use os.expanduser instead, but this is not permanent.

URL has double slashes when using os.path.join ; use urljoin from urllib.parse instead. However, this method joins 2 or 3 arguments only.

There are likely others, will update as they are found.

**Comment by s-kganz** [comment]
requests_retry_session returns NoneType, somehow gets around while loop in m2m.py

![requests_retry_session](https://user-images.githubusercontent.com/38630604/41740218-30fd34a6-754c-11e8-8486-8cb35c6d4f61.png)

**Comment by lsetiawan** [comment]
@s-kganz Is this using PR #33

**Comment by s-kganz** [comment]
@lsetiawan yes, on branch fix_windows

**Comment by s-kganz** [comment]
issue with NoneType data request resolved, requires using own creds
