### ISSUE TITLE
(Windows) Fails to download OOI streams on conversion to xarray

### ISSUE THREAD

**Issue by s-kganz** [cormorack/yodapy#34]
requests.exceptions.RetryError: None: Max retries exceeded with url: /async_results/s-kganz@lwsd.org/20180621T205904-RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample%5Cstatus.txt (Caused by None)

**Comment by s-kganz** [comment]
maybe missing first part of url?

**Comment by s-kganz** [comment]
According to [this](https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url) it may be OOI refusing due to too many requests. Also see [this issue](https://github.com/requests/requests/issues/1198).

**Comment by s-kganz** [comment]
issue apparently linked to current load on API, not related to yodapy package

**Comment by lsetiawan** [comment]
Issue resolved in #35
