### ISSUE TITLE
Stream EndTime not available, disagreement with data portal

### ISSUE THREAD

**Issue by s-kganz** [cormorack/yodapy#43]
On request from instrument CE09OSSM-RID26-07-NUTNRB000, data portal shows availability for March 29-30, 2018. However, making a request through yodapy raises a warning that the date is out of range.

```
start = "2018-03-29"
stop = "2018-03-30"

ooi.filter(region="coastal endurance",instrument="CE09OSSM-RID26-07-NUTNRB000")

ooi.request_data(begin_date=start, end_date=stop,limit=1,data_type="json")
```
Gives the error:
```
CE09OSSM-RID26-07-NUTNRB000-nutnr_b_dcl_conc_instrument time check - End time exceeds stream endTime
CE09OSSM-RID26-07-NUTNRB000-nutnr_b_dcl_conc_instrument time check - Setting request end time to stream endTime
CE09OSSM-RID26-07-NUTNRB000-nutnr_b_dcl_conc_instrument - Invalid time range specified
```
And results in a IndexError:
```
c:\users\ganzk\desktop\yodapy\yodapy\yodapy\datasources\ooi\__init__.py in <lambda>(inst)
    276                                                                               application_type=data_type,
    277                                                                               limit=limit,
--> 278                                                                               **kwargs)[0],
    279                                 do_filter))
    280 

IndexError: list index out of range
```

**Comment by lsetiawan** [comment]
Checking the actual stream and method on the data portal, this is actually a valid error. `CE09OSSM-RID26-07-NUTNRB000-nutnr_b_dcl_conc_instrument` have a time range of ` 2015-04-09 17:30:00.000  -  2016-07-14 05:30:46.498 ` This is also consistent with the M2M checks. 

When the same function is ran with `start='2013-03-29'` I get
```
[{'message': {'status': '{\n  "message": "Unexpected internal error during request", \n  "requestUUID": "3cfe7a09-d62b-4bba-b794-5ced92e849f9"\n}\n'},
  'status_code': 500}]
```

When I change `limit=10`, actual data can be retrieved. I guess the number of data point has a limit for this dataset. I am thinking of possibly create a minimum of 10 data points!

With this discovery, this is not really a bug. Though a more helpful error might be needed.
