### ISSUE TITLE
Merged instrument datasets result in NaNs for non-identical time series.

### ISSUE THREAD

**Issue by s-kganz** [cormorack/yodapy#60]
A data request from multiple instruments with non-identical time series results in some variables becoming all NaNs.

Example: 
`nooi = OOI()`
`nooi.search(region="coastal endurance",instrument="ctd,nitrate",node="shallow profiler")`
...
`nooi.to_xarray()`
`nooi.to_dataframe()`
...
```
nooi[1]["salinity_corrected_nitrate"][:5]
>>>[NaN,NaN,NaN,NaN,NaN]
```

**Comment by lsetiawan** [comment]
I tried this out and I'm getting actual values. See screenshot below. Thanks.

![screenshot from 2018-08-02 14-01-20](https://user-images.githubusercontent.com/17802172/43611388-d079fbe0-965d-11e8-9184-4b518e0ac0d2.png)

**Comment by s-kganz** [comment]
Works properly as described above. Nitrate nbk can move forward now, yay!
