### ISSUE TITLE
Multiple data requests result in hanging forever for functions beyond `request_data`

### ISSUE THREAD

**Issue by s-kganz** [cormorack/yodapy#62]
Calling `to_xarray` on a second OOI object after having previously called `to_xarray` and `to_dataframe` on a different OOI object results in the method call hanging forever.
I.e.,
```
ooi1.search(...
ooi1.request_data(...
ooi1.to_xarray()
```
works as intended. Then, either with the same `OOI` object or a different `OOI` object, `ooi2`, the `search` and `request_data` functions work as intended. However, calling `to_xarray` on `ooi2` will cause the kernel to hang for upwards of an hour. Also, the `Request completed` warning that is normally printed on a `to_xarray` call will not appear on the second request.

This was observed also when the first object was deleted using `del`.

**Comment by s-kganz** [comment]
Update: issue appears to lie with how the second object checks readiness of data request.

After firing `data_request`, the `check_status` function will always return -1 despite `status.txt` at the url showing `complete`.

I.e.,

```
status = -1
while status < 0:
    status = nooi.check_status()[0]
    time.sleep(5)
    print("waiting")
```
Will print "waiting" forever, where nooi is a second OOI object.

**Comment by lsetiawan** [comment]
To help me debug this, could you please do the same workflow, this time look at the actual `ooi.raw()` for each one. Paste the results here.

**Comment by s-kganz** [comment]
No longer able to reproduce. Closing for now.
